
interface CompetitorData {
  id: string;
  url: string;
  name: string;
  isYourSite?: boolean;
  metrics: {
    seoScore: number;
    pageSpeed: number;
    mobileScore: number;
    uxScore: number;
    contentScore: number;
    ctaCount: number;
    loadTime: number;
    conversionRate: number;
    trustSignals: number;
  };
  strengths: string[];
  weaknesses: string[];
  recommendations: string[];
}

export const generateReport = (analysisData: CompetitorData[]): string => {
  const currentDate = new Date().toLocaleDateString();
  const yourSite = analysisData.find(d => d.isYourSite);
  const competitors = analysisData.filter(d => !d.isYourSite);

  let report = `COMPETITOR ANALYSIS REPORT
Generated on: ${currentDate}

EXECUTIVE SUMMARY
=================
This report analyzes ${analysisData.length} websites, including your site and ${competitors.length} competitor(s).

YOUR WEBSITE OVERVIEW
====================
Website: ${yourSite?.name || 'Your Website'}
URL: ${yourSite?.url || 'N/A'}

Performance Metrics:
- SEO Score: ${yourSite?.metrics.seoScore || 0}/100
- Page Speed: ${yourSite?.metrics.pageSpeed || 0}/100
- Mobile Score: ${yourSite?.metrics.mobileScore || 0}/100
- UX Score: ${yourSite?.metrics.uxScore || 0}/100
- Content Score: ${yourSite?.metrics.contentScore || 0}/100
- Load Time: ${yourSite?.metrics.loadTime || 0}s
- Conversion Rate: ${yourSite?.metrics.conversionRate || 0}%
- CTA Count: ${yourSite?.metrics.ctaCount || 0}
- Trust Signals: ${yourSite?.metrics.trustSignals || 0}

Strengths:
${yourSite?.strengths.map(s => `• ${s}`).join('\n') || '• No strengths identified'}

Areas for Improvement:
${yourSite?.weaknesses.map(w => `• ${w}`).join('\n') || '• No weaknesses identified'}

COMPETITOR ANALYSIS
==================
`;

  competitors.forEach((competitor, index) => {
    report += `
${index + 1}. ${competitor.name}
${'='.repeat(competitor.name.length + 3)}
URL: ${competitor.url}

Performance Metrics:
- SEO Score: ${competitor.metrics.seoScore}/100
- Page Speed: ${competitor.metrics.pageSpeed}/100
- Mobile Score: ${competitor.metrics.mobileScore}/100
- UX Score: ${competitor.metrics.uxScore}/100
- Content Score: ${competitor.metrics.contentScore}/100
- Load Time: ${competitor.metrics.loadTime}s
- Conversion Rate: ${competitor.metrics.conversionRate}%
- CTA Count: ${competitor.metrics.ctaCount}
- Trust Signals: ${competitor.metrics.trustSignals}

Strengths:
${competitor.strengths.map(s => `• ${s}`).join('\n')}

Weaknesses:
${competitor.weaknesses.map(w => `• ${w}`).join('\n')}

Key Learnings:
${competitor.recommendations.map(r => `• ${r}`).join('\n')}
`;
  });

  // Gap Analysis
  if (yourSite) {
    report += `

GAP ANALYSIS
============
Areas where competitors outperform your website:

`;

    const gaps = [];
    competitors.forEach(competitor => {
      Object.entries(competitor.metrics).forEach(([metric, value]) => {
        const yourValue = yourSite.metrics[metric as keyof typeof yourSite.metrics];
        if (typeof value === 'number' && typeof yourValue === 'number' && value > yourValue) {
          const gap = value - yourValue;
          gaps.push({
            metric: metric.replace(/([A-Z])/g, ' $1').replace(/^./, str => str.toUpperCase()),
            competitor: competitor.name,
            gap: gap,
            yourValue,
            theirValue: value
          });
        }
      });
    });

    const sortedGaps = gaps.sort((a, b) => b.gap - a.gap).slice(0, 10);
    
    if (sortedGaps.length > 0) {
      sortedGaps.forEach(gap => {
        report += `• ${gap.metric}: You (${gap.yourValue}) vs ${gap.competitor} (${gap.theirValue}) - Gap: ${gap.gap.toFixed(1)} points
`;
      });
    } else {
      report += `• No significant gaps identified - your website performs competitively across all metrics!
`;
    }
  }

  report += `

RECOMMENDATIONS
===============
Based on this analysis, here are the top recommendations:

`;

  if (yourSite) {
    yourSite.recommendations.forEach((rec, index) => {
      report += `${index + 1}. ${rec}
`;
    });
  }

  report += `

METHODOLOGY
===========
This analysis was conducted using automated web auditing tools that evaluate:
- SEO optimization and meta tag quality
- Page loading speed and performance metrics
- Mobile responsiveness and user experience
- Content quality and engagement factors
- Call-to-action effectiveness
- Trust signal presence and authority markers

For questions about this report, please contact your web development team.

---
Report generated by Competitor Analysis Tool
${currentDate}
`;

  return report;
};

export const downloadReport = (reportContent: string, filename: string = 'competitor-analysis-report.txt') => {
  const blob = new Blob([reportContent], { type: 'text/plain;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
};
